/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.nio.file.Path;

import org.apache.catalina.Context;
import org.apache.catalina.WebResourceRoot;
import org.apache.catalina.startup.Tomcat;
import org.apache.catalina.webresources.DirResourceSet;
import org.apache.catalina.webresources.StandardRoot;
import org.example.controller.FeedServlet;
import org.example.controller.LikeServlet;
import org.example.controller.LoginServlet;
import org.example.controller.LogoutServlet;
import org.example.controller.PostDetailServlet;
import org.example.controller.PostServlet;
import org.example.controller.RegisterServlet;

public class App {
    public static void main(String[] args) throws Exception {
        Path projectRoot = resolveProjectRoot();
        File webappDir = projectRoot.resolve("src/main/webapp").toFile();
        File classesDir = projectRoot.resolve("build/classes/java/main").toFile();

        System.out.println("webapp dir : " + webappDir.getAbsolutePath());
        System.out.println("classes dir: " + classesDir.getAbsolutePath());

        Tomcat tomcat = new Tomcat();
        tomcat.setPort(8080);
        tomcat.getConnector();

        Context ctx = tomcat.addWebapp("", webappDir.getAbsolutePath());

        WebResourceRoot resources = new StandardRoot(ctx);
        resources.addPreResources(new DirResourceSet(
                resources,
                "/WEB-INF/classes",
                classesDir.getAbsolutePath(),
                "/"));
        ctx.setResources(resources);

        Tomcat.addServlet(ctx, "feedServlet", new FeedServlet());
        ctx.addServletMappingDecoded("/feed", "feedServlet");

        Tomcat.addServlet(ctx, "loginServlet", new LoginServlet());
        ctx.addServletMappingDecoded("/login", "loginServlet");

        Tomcat.addServlet(ctx, "registerServlet", new RegisterServlet());
        ctx.addServletMappingDecoded("/register", "registerServlet");

        Tomcat.addServlet(ctx, "logoutServlet", new LogoutServlet());
        ctx.addServletMappingDecoded("/logout", "logoutServlet");

        Tomcat.addServlet(ctx, "postServlet", new PostServlet());
        ctx.addServletMappingDecoded("/post", "postServlet");

        Tomcat.addServlet(ctx, "postDetailServlet", new PostDetailServlet());
        ctx.addServletMappingDecoded("/post-detail", "postDetailServlet");

        Tomcat.addServlet(ctx, "likeServlet", new LikeServlet());
        ctx.addServletMappingDecoded("/like", "likeServlet");

        tomcat.start();
        System.out.println("Miniature started on http://localhost:8080");
        tomcat.getServer().await();
    }

    public String getGreeting() {
        return "Hello World!";
    }

    private static Path resolveProjectRoot() {
        return Path.of(System.getProperty("user.dir"));
    }
}
