/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.infrastructure.config.TomcatServerStart;

public class App {
    public static void main(String[] args) throws Exception {


        // AT THE END OF THE PROGRAM
        TomcatServerStart
            .create()
            .createWebapp()
            .mapServlets()
            .build();
    }
    public String getGreeting() {
        return "Hello World!";
    }
}
